#+TITLE: グローバル理工丼
#+AUTHOR: mamonbo

* これなんですの?
実況用twitterクライアント
[[https://github.com/ymduu/G_rikou][グローバル理工兄弟]]
の
[[https://github.com/tootsuite/mastodon][mastodon]]
版

* Requirements
** python
  3を想定しております(当たり前だよなあ)
** [[https://github.com/halcy/Mastodon.py][Mastodon.py]]
  導入については、本家参照
** wxPython
   PyPIにて入手可能
   
   ~pip install wxpython~
** Pillow
   こちらもPyPIにて入手可能

   PILはpython 2にしか無いのでPillowを使います

   ~pip install pillow~
* Usage
** クライアント起動まで
*** このリポジトリをクローンする または リリースを貰ってくる(あれば)
*** ~user.json~ を自分のアカウント用に書き換える
 #+BEGIN_SRC js
 {
     "url":"<インスタンスのURL>",
     "usermail":"<アカウントのメールアドレス>",
     "password":"<パスワード>"
 }
 #+END_SRC

*** トークンを生成する
 ~python token_generator.py~

 成功していれば ~client_cred.txt~ と ~user_cred.txt~ が生成される。
 アカウント変更するときも、 ~user.json~ を書き換えて
 ~token_generator.py~
 を実行する。

 ここまで初回時のみ必要
*** クライアントを起動する
 ~python otaku_client.py~
**** 注意
    こちらの環境では eshell 上ではGUIが立ち上がらなかった

** クライアントの使用方法
実況に使いたいタグを追加ボタンの上にある入力欄に入力し、
タグ1追加/タグ2追加ボタンでテキストファイル(subjects.txt/channels.txt)
にセーブします。
一度セーブしたタグは選択肢から選択して何度でも利用することができます。
あとは入力欄にツイートしたい内容を入力し、postボタンかEnterキーで投稿するだけです。かんたん。
タグをつけたくない時は選択肢の中の空白を選択してください。
** 登録タグについて
一度追加したタグを削除するには、お手数ですがsubjects.txt/channels.txt
から追加したタグを削除してください。
タグ2にはあらかじめ東京のテレビ局のタグを登録してありますが、
利用しない場合は変更していただいてかまいません。

* Acknowledgements
** ymduu
   twitter 版グローバル理工兄弟の作者
   [[https://github.com/ymduu][github]]
   [[https://mobile.twitter.com/ymduu][twitter🔒]]
** 末代の人々(https://mstdn.maud.io)
   mastodon に詳しい人たちが居たり、サーバ管理者との交流が盛んだったり
  
